name: Terraform Apply (Promotion Pipeline)

on:
  workflow_dispatch:
    inputs:
      cloud:
        description: "Target cloud provider"
        required: true
        type: choice
        options: [aws, gcp]

jobs:
# =====================
# DEV
# =====================
  plan-dev:
    uses: ./.github/workflows/terraform-run.yml
    with:
      environment: dev
      cloud: ${{ inputs.cloud }}
      action: plan

  apply-dev:
    needs: plan-dev
    uses: ./.github/workflows/terraform-run.yml
    with:
      environment: dev
      cloud: ${{ inputs.cloud }}
      action: apply

# =====================
# STAGE
# =====================
  plan-stage:
    needs: apply-dev
    uses: ./.github/workflows/terraform-run.yml
    with:
      environment: stage
      cloud: ${{ inputs.cloud }}
      action: plan

  apply-stage:
    needs: plan-stage
    uses: ./.github/workflows/terraform-run.yml
    with:
      environment: stage
      cloud: ${{ inputs.cloud }}
      action: apply

# =====================
# PROD
# =====================
  plan-prod:
    needs: apply-stage
    uses: ./.github/workflows/terraform-run.yml
    with:
      environment: prod
      cloud: ${{ inputs.cloud }}
      action: plan

  apply-prod:
    needs: plan-prod
    uses: ./.github/workflows/terraform-run.yml
    with:
      environment: prod
      cloud: ${{ inputs.cloud }}
      action: apply
